-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.assignments (
  id bigint NOT NULL DEFAULT nextval('assignments_id_seq'::regclass),
  assignment_date date NOT NULL,
  custodian_id uuid NOT NULL,
  title text,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'submitted'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  eod_signed boolean DEFAULT false,
  eod_signed_at timestamp with time zone,
  eod_signature_url text,
  CONSTRAINT assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assignments_custodian_id_fkey FOREIGN KEY (custodian_id) REFERENCES auth.users(id)
);
CREATE TABLE public.atm_cash_adjustments (
  id bigint NOT NULL DEFAULT nextval('atm_cash_adjustments_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  site_id bigint NOT NULL,
  adjustment_type text NOT NULL DEFAULT 'withdrawal'::text,
  denom_100 integer DEFAULT 0,
  denom_200 integer DEFAULT 0,
  denom_500 integer DEFAULT 0,
  denom_2000 integer DEFAULT 0,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  geo_lat numeric,
  geo_lng numeric,
  distance_meters numeric,
  photo_url text,
  CONSTRAINT atm_cash_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT atm_cash_adjustments_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT atm_cash_adjustments_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT atm_cash_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.atm_excess_cash (
  id bigint NOT NULL DEFAULT nextval('atm_excess_cash_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  site_id bigint NOT NULL,
  detected_date date NOT NULL DEFAULT CURRENT_DATE,
  denom_100 integer DEFAULT 0,
  denom_200 integer DEFAULT 0,
  denom_500 integer DEFAULT 0,
  denom_2000 integer DEFAULT 0,
  total_excess_amount numeric DEFAULT ((((denom_100 * 100) + (denom_200 * 200)) + (denom_500 * 500)) + (denom_2000 * 2000)),
  atm_receipt_url text NOT NULL,
  reported_to_vendor boolean DEFAULT false,
  vendor_ticket_no text,
  bank_notified boolean DEFAULT false,
  bank_reference_no text,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  gps_status text,
  gps_lat numeric,
  gps_lng numeric,
  gps_distance_meters numeric,
  gps_photo_url text,
  gps_verified_at timestamp with time zone,
  excess_date date,
  recon_communication_date date,
  CONSTRAINT atm_excess_cash_pkey PRIMARY KEY (id),
  CONSTRAINT atm_excess_assignment_fk FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT atm_excess_site_fk FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.atm_removal_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id integer NOT NULL UNIQUE,
  denom_2000 integer NOT NULL DEFAULT 0,
  denom_500 integer NOT NULL DEFAULT 0,
  denom_200 integer NOT NULL DEFAULT 0,
  denom_100 integer NOT NULL DEFAULT 0,
  denom_50 integer NOT NULL DEFAULT 0,
  denom_20 integer NOT NULL DEFAULT 0,
  denom_10 integer NOT NULL DEFAULT 0,
  remarks text NOT NULL DEFAULT ''::text,
  has_source_report boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT atm_removal_plans_pkey PRIMARY KEY (id),
  CONSTRAINT atm_removal_plans_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id)
);
CREATE TABLE public.atm_replenishments (
  id bigint NOT NULL DEFAULT nextval('atm_replenishments_id_seq'::regclass),
  assignment_id bigint,
  site_id bigint,
  time_in timestamp with time zone,
  time_out timestamp with time zone,
  denom_2000 integer DEFAULT 0,
  denom_500 integer DEFAULT 0,
  denom_200 integer DEFAULT 0,
  denom_100 integer DEFAULT 0,
  denom_50 integer DEFAULT 0,
  denom_20 integer DEFAULT 0,
  denom_10 integer DEFAULT 0,
  closing_balance numeric,
  remarks text,
  receipt_url text,
  created_at timestamp with time zone DEFAULT now(),
  load_lat numeric,
  load_lng numeric,
  distance_meters numeric,
  geo_status text DEFAULT 'unknown'::text,
  photo_required boolean DEFAULT false,
  photo_url text,
  source_breakdown jsonb,
  CONSTRAINT atm_replenishments_pkey PRIMARY KEY (id),
  CONSTRAINT atm_replenishments_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT atm_replenishments_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  entity text,
  entity_id bigint,
  action text,
  actor uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_name text NOT NULL CHECK (length(TRIM(BOTH FROM bank_name)) > 0),
  account_number text NOT NULL CHECK (length(TRIM(BOTH FROM account_number)) > 0),
  ifsc_code text NOT NULL CHECK (length(TRIM(BOTH FROM ifsc_code)) > 0),
  branch_code text,
  branch_name text,
  branch_phone text,
  branch_email text,
  branch_address text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  latitude numeric,
  longitude numeric,
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT bank_accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.bank_denomination_plans (
  id bigint NOT NULL DEFAULT nextval('bank_denomination_plans_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  bank_account_id uuid NOT NULL,
  denom_2000 integer NOT NULL DEFAULT 0,
  denom_500 integer NOT NULL DEFAULT 0,
  denom_200 integer NOT NULL DEFAULT 0,
  denom_100 integer NOT NULL DEFAULT 0,
  denom_50 integer NOT NULL DEFAULT 0,
  denom_20 integer NOT NULL DEFAULT 0,
  denom_10 integer NOT NULL DEFAULT 0,
  remarks text,
  has_source_report boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_denomination_plans_pkey PRIMARY KEY (id),
  CONSTRAINT bank_denomination_plans_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT bank_denomination_plans_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.banks (
  id bigint NOT NULL DEFAULT nextval('banks_id_seq'::regclass),
  name text NOT NULL,
  branch text NOT NULL,
  short_code text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT banks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cash_pickups (
  id bigint NOT NULL DEFAULT nextval('cash_pickups_id_seq'::regclass),
  assignment_id bigint,
  bank_name text,
  branch text,
  pickup_time timestamp with time zone DEFAULT now(),
  denom_2000 integer DEFAULT 0,
  denom_500 integer DEFAULT 0,
  denom_200 integer DEFAULT 0,
  denom_100 integer DEFAULT 0,
  denom_50 integer DEFAULT 0,
  denom_20 integer DEFAULT 0,
  denom_10 integer DEFAULT 0,
  expected_amount numeric,
  total_amount numeric,
  variance numeric,
  slip_url text,
  created_at timestamp with time zone DEFAULT now(),
  internal_source_metadata jsonb,
  pickup_source text DEFAULT 'BANK'::text CHECK (pickup_source = ANY (ARRAY['BANK'::text, 'ATM_INTERNAL'::text])),
  source_site_id bigint,
  gps_metadata jsonb,
  gps_photo_url text,
  cheque_number text,
  cheque_image_url text,
  cheque_verified boolean DEFAULT false,
  cheque_verified_by uuid,
  cheque_verified_at timestamp with time zone,
  cheque_status text DEFAULT 'PENDING'::text CHECK (cheque_status = ANY (ARRAY['PENDING'::text, 'VERIFIED'::text, 'REJECTED'::text, 'CLEARED'::text])),
  cheque_metadata jsonb,
  CONSTRAINT cash_pickups_pkey PRIMARY KEY (id),
  CONSTRAINT cash_pickups_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT cash_pickups_source_site_id_fkey FOREIGN KEY (source_site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.cheque_audit_log (
  id bigint NOT NULL DEFAULT nextval('cheque_audit_log_id_seq'::regclass),
  pickup_id bigint NOT NULL,
  old_status text DEFAULT 'PENDING'::text,
  new_status text NOT NULL CHECK (new_status = ANY (ARRAY['PENDING'::text, 'VERIFIED'::text, 'REJECTED'::text, 'CLEARED'::text])),
  old_verified_by uuid,
  new_verified_by uuid,
  change_reason text,
  metadata jsonb,
  updated_by uuid NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cheque_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT cheque_audit_log_pickup_id_fkey FOREIGN KEY (pickup_id) REFERENCES public.cash_pickups(id)
);
CREATE TABLE public.denomination_plans (
  id bigint NOT NULL DEFAULT nextval('denomination_plans_id_seq'::regclass),
  assignment_id bigint,
  site_id bigint,
  has_source_report boolean DEFAULT true,
  remarks text,
  denom_2000 integer DEFAULT 0,
  denom_500 integer DEFAULT 0,
  denom_200 integer DEFAULT 0,
  denom_100 integer DEFAULT 0,
  denom_50 integer DEFAULT 0,
  denom_20 integer DEFAULT 0,
  denom_10 integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT denomination_plans_pkey PRIMARY KEY (id),
  CONSTRAINT denomination_plans_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT denomination_plans_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  role text DEFAULT 'custodian'::text CHECK (role = ANY (ARRAY['admin'::text, 'supervisor'::text, 'custodian'::text])),
  created_at timestamp with time zone DEFAULT now(),
  first_login boolean DEFAULT true,
  email text NOT NULL,
  mobile_number text,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  deletion_reason text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.route_sites (
  id bigint NOT NULL DEFAULT nextval('route_sites_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  site_id bigint NOT NULL,
  sequence_no integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT route_sites_pkey PRIMARY KEY (id),
  CONSTRAINT route_sites_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT route_sites_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.sites (
  id bigint NOT NULL DEFAULT nextval('sites_id_seq'::regclass),
  site_code text NOT NULL UNIQUE,
  atm_id text,
  bank_name text,
  address text,
  city text,
  created_at timestamp with time zone DEFAULT now(),
  latitude numeric,
  longitude numeric,
  CONSTRAINT sites_pkey PRIMARY KEY (id)
);
CREATE TABLE public.soa_adjustments (
  id bigint NOT NULL DEFAULT nextval('soa_adjustments_id_seq'::regclass),
  soa_id bigint NOT NULL,
  assignment_id bigint NOT NULL,
  custodian_id uuid NOT NULL,
  adjustment_type text NOT NULL CHECK (adjustment_type = ANY (ARRAY['CREDIT'::text, 'DEBIT'::text, 'EXCHANGE'::text, 'INTER_SITE_TRANSFER'::text])),
  adjustment_amount numeric NOT NULL,
  reason text NOT NULL,
  reference text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid NOT NULL,
  exchange_metadata jsonb,
  transfer_metadata jsonb,
  requires_custodian_confirmation boolean DEFAULT true,
  custodian_confirmed boolean DEFAULT false,
  custodian_confirmed_at timestamp with time zone,
  custodian_signature_url text,
  original_reference_snapshot jsonb,
  CONSTRAINT soa_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT soa_adjustments_assignment_fk FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT soa_adjustments_custodian_fk FOREIGN KEY (custodian_id) REFERENCES auth.users(id),
  CONSTRAINT soa_adjustments_soa_fk FOREIGN KEY (soa_id) REFERENCES public.assignments(id)
);
CREATE TABLE public.soa_ledger (
  id bigint NOT NULL DEFAULT nextval('soa_ledger_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  custodian_id uuid NOT NULL,
  entry_date date NOT NULL,
  entry_time timestamp with time zone NOT NULL DEFAULT now(),
  source_table text NOT NULL,
  source_id bigint NOT NULL,
  event_type text NOT NULL,
  site_id bigint,
  amount numeric NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text])),
  running_balance numeric,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT soa_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT soa_ledger_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT soa_ledger_custodian_id_fkey FOREIGN KEY (custodian_id) REFERENCES auth.users(id),
  CONSTRAINT soa_ledger_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.soa_postings (
  id bigint NOT NULL DEFAULT nextval('soa_postings_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  custodian_id uuid NOT NULL,
  assignment_date date NOT NULL,
  cash_picked numeric NOT NULL DEFAULT 0,
  cash_loaded numeric NOT NULL DEFAULT 0,
  cash_adjusted numeric NOT NULL DEFAULT 0,
  excess_reported numeric NOT NULL DEFAULT 0,
  travel_km numeric NOT NULL DEFAULT 0,
  travel_allowance numeric NOT NULL DEFAULT 0,
  net_cash_position numeric NOT NULL,
  eod_signed boolean NOT NULL DEFAULT false,
  eod_signed_at timestamp with time zone,
  eod_signature_url text,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  posted_by uuid NOT NULL,
  source text NOT NULL DEFAULT 'eod_approval'::text,
  CONSTRAINT soa_postings_pkey PRIMARY KEY (id),
  CONSTRAINT soa_postings_assignment_fk FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT soa_postings_custodian_fk FOREIGN KEY (custodian_id) REFERENCES auth.users(id)
);
CREATE TABLE public.system_settings (
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.technical_issues (
  id bigint NOT NULL DEFAULT nextval('technical_issues_id_seq'::regclass),
  assignment_id bigint,
  site_id bigint,
  issue_type text,
  error_code text,
  description text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'in_progress'::text, 'resolved'::text])),
  photo_url text,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT technical_issues_pkey PRIMARY KEY (id),
  CONSTRAINT technical_issues_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT technical_issues_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.travel_logs (
  id bigint NOT NULL DEFAULT nextval('travel_logs_id_seq'::regclass),
  assignment_id bigint NOT NULL,
  site_id bigint,
  custodian_id uuid,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  odometer_start numeric,
  odometer_end numeric,
  km_covered numeric,
  gps_start_lat numeric,
  gps_start_lng numeric,
  gps_end_lat numeric,
  gps_end_lng numeric,
  status text DEFAULT 'in_progress'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vehicle_type text,
  source text CHECK (source = ANY (ARRAY['gps'::text, 'odometer'::text])),
  allowance_amount numeric,
  updated_at timestamp with time zone DEFAULT now(),
  rate_per_km numeric,
  CONSTRAINT travel_logs_pkey PRIMARY KEY (id),
  CONSTRAINT travel_logs_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT travel_logs_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT travel_logs_custodian_id_fkey FOREIGN KEY (custodian_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vehicle_rates (
  vehicle_type text NOT NULL,
  rate_per_km numeric NOT NULL,
  active boolean DEFAULT true,
  CONSTRAINT vehicle_rates_pkey PRIMARY KEY (vehicle_type)
);
-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE auth.audit_log_entries (
  instance_id uuid,
  id uuid NOT NULL,
  payload json,
  created_at timestamp with time zone,
  ip_address character varying NOT NULL DEFAULT ''::character varying,
  CONSTRAINT audit_log_entries_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.custom_oauth_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_type text NOT NULL CHECK (provider_type = ANY (ARRAY['oauth2'::text, 'oidc'::text])),
  identifier text NOT NULL UNIQUE CHECK (identifier ~ '^[a-z0-9][a-z0-9:-]{0,48}[a-z0-9]$'::text),
  name text NOT NULL CHECK (char_length(name) >= 1 AND char_length(name) <= 100),
  client_id text NOT NULL CHECK (char_length(client_id) >= 1 AND char_length(client_id) <= 512),
  client_secret text NOT NULL,
  acceptable_client_ids ARRAY NOT NULL DEFAULT '{}'::text[],
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  pkce_enabled boolean NOT NULL DEFAULT true,
  attribute_mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
  authorization_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled boolean NOT NULL DEFAULT true,
  email_optional boolean NOT NULL DEFAULT false,
  issuer text CHECK (issuer IS NULL OR char_length(issuer) >= 1 AND char_length(issuer) <= 2048),
  discovery_url text CHECK (discovery_url IS NULL OR char_length(discovery_url) <= 2048),
  skip_nonce_check boolean NOT NULL DEFAULT false,
  cached_discovery jsonb,
  discovery_cached_at timestamp with time zone,
  authorization_url text CHECK (authorization_url IS NULL OR authorization_url ~~ 'https://%'::text),
  token_url text CHECK (token_url IS NULL OR token_url ~~ 'https://%'::text),
  userinfo_url text CHECK (userinfo_url IS NULL OR userinfo_url ~~ 'https://%'::text),
  jwks_uri text CHECK (jwks_uri IS NULL OR jwks_uri ~~ 'https://%'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_oauth_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.flow_state (
  id uuid NOT NULL,
  user_id uuid,
  auth_code text,
  code_challenge_method USER-DEFINED,
  code_challenge text,
  provider_type text NOT NULL,
  provider_access_token text,
  provider_refresh_token text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  authentication_method text NOT NULL,
  auth_code_issued_at timestamp with time zone,
  invite_token text,
  referrer text,
  oauth_client_state_id uuid,
  linking_target_id uuid,
  email_optional boolean NOT NULL DEFAULT false,
  CONSTRAINT flow_state_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.identities (
  provider_id text NOT NULL,
  user_id uuid NOT NULL,
  identity_data jsonb NOT NULL,
  provider text NOT NULL,
  last_sign_in_at timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  email text DEFAULT lower((identity_data ->> 'email'::text)),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT identities_pkey PRIMARY KEY (id),
  CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.instances (
  id uuid NOT NULL,
  uuid uuid,
  raw_base_config text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT instances_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.mfa_amr_claims (
  session_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  authentication_method text NOT NULL,
  id uuid NOT NULL,
  CONSTRAINT mfa_amr_claims_pkey PRIMARY KEY (id),
  CONSTRAINT mfa_amr_claims_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id)
);
CREATE TABLE auth.mfa_challenges (
  id uuid NOT NULL,
  factor_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  ip_address inet NOT NULL,
  otp_code text,
  web_authn_session_data jsonb,
  CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT mfa_challenges_auth_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES auth.mfa_factors(id)
);
CREATE TABLE auth.mfa_factors (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  friendly_name text,
  factor_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  secret text,
  phone text,
  last_challenged_at timestamp with time zone UNIQUE,
  web_authn_credential jsonb,
  web_authn_aaguid uuid,
  last_webauthn_challenge_data jsonb,
  CONSTRAINT mfa_factors_pkey PRIMARY KEY (id),
  CONSTRAINT mfa_factors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.oauth_authorizations (
  id uuid NOT NULL,
  authorization_id text NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  user_id uuid,
  redirect_uri text NOT NULL CHECK (char_length(redirect_uri) <= 2048),
  scope text NOT NULL CHECK (char_length(scope) <= 4096),
  state text CHECK (char_length(state) <= 4096),
  resource text CHECK (char_length(resource) <= 2048),
  code_challenge text CHECK (char_length(code_challenge) <= 128),
  code_challenge_method USER-DEFINED,
  response_type USER-DEFINED NOT NULL DEFAULT 'code'::auth.oauth_response_type,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::auth.oauth_authorization_status,
  authorization_code text UNIQUE CHECK (char_length(authorization_code) <= 255),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:03:00'::interval),
  approved_at timestamp with time zone,
  nonce text CHECK (char_length(nonce) <= 255),
  CONSTRAINT oauth_authorizations_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_authorizations_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id),
  CONSTRAINT oauth_authorizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.oauth_client_states (
  id uuid NOT NULL,
  provider_type text NOT NULL,
  code_verifier text,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT oauth_client_states_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.oauth_clients (
  id uuid NOT NULL,
  client_secret_hash text,
  registration_type USER-DEFINED NOT NULL,
  redirect_uris text NOT NULL,
  grant_types text NOT NULL,
  client_name text CHECK (char_length(client_name) <= 1024),
  client_uri text CHECK (char_length(client_uri) <= 2048),
  logo_uri text CHECK (char_length(logo_uri) <= 2048),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  client_type USER-DEFINED NOT NULL DEFAULT 'confidential'::auth.oauth_client_type,
  token_endpoint_auth_method text NOT NULL CHECK (token_endpoint_auth_method = ANY (ARRAY['client_secret_basic'::text, 'client_secret_post'::text, 'none'::text])),
  CONSTRAINT oauth_clients_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.oauth_consents (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  client_id uuid NOT NULL,
  scopes text NOT NULL CHECK (char_length(scopes) <= 2048),
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT oauth_consents_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT oauth_consents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id)
);
CREATE TABLE auth.one_time_tokens (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  token_type USER-DEFINED NOT NULL,
  token_hash text NOT NULL CHECK (char_length(token_hash) > 0),
  relates_to text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT one_time_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT one_time_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.refresh_tokens (
  instance_id uuid,
  id bigint NOT NULL DEFAULT nextval('auth.refresh_tokens_id_seq'::regclass),
  token character varying UNIQUE,
  user_id character varying,
  revoked boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  parent character varying,
  session_id uuid,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id)
);
CREATE TABLE auth.saml_providers (
  id uuid NOT NULL,
  sso_provider_id uuid NOT NULL,
  entity_id text NOT NULL UNIQUE CHECK (char_length(entity_id) > 0),
  metadata_xml text NOT NULL CHECK (char_length(metadata_xml) > 0),
  metadata_url text CHECK (metadata_url = NULL::text OR char_length(metadata_url) > 0),
  attribute_mapping jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  name_id_format text,
  CONSTRAINT saml_providers_pkey PRIMARY KEY (id),
  CONSTRAINT saml_providers_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id)
);
CREATE TABLE auth.saml_relay_states (
  id uuid NOT NULL,
  sso_provider_id uuid NOT NULL,
  request_id text NOT NULL CHECK (char_length(request_id) > 0),
  for_email text,
  redirect_to text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  flow_state_id uuid,
  CONSTRAINT saml_relay_states_pkey PRIMARY KEY (id),
  CONSTRAINT saml_relay_states_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id),
  CONSTRAINT saml_relay_states_flow_state_id_fkey FOREIGN KEY (flow_state_id) REFERENCES auth.flow_state(id)
);
CREATE TABLE auth.schema_migrations (
  version character varying NOT NULL,
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);
CREATE TABLE auth.sessions (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  factor_id uuid,
  aal USER-DEFINED,
  not_after timestamp with time zone,
  refreshed_at timestamp without time zone,
  user_agent text,
  ip inet,
  tag text,
  oauth_client_id uuid,
  refresh_token_hmac_key text,
  refresh_token_counter bigint,
  scopes text CHECK (char_length(scopes) <= 4096),
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES auth.oauth_clients(id)
);
CREATE TABLE auth.sso_domains (
  id uuid NOT NULL,
  sso_provider_id uuid NOT NULL,
  domain text NOT NULL CHECK (char_length(domain) > 0),
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT sso_domains_pkey PRIMARY KEY (id),
  CONSTRAINT sso_domains_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id)
);
CREATE TABLE auth.sso_providers (
  id uuid NOT NULL,
  resource_id text CHECK (resource_id = NULL::text OR char_length(resource_id) > 0),
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  disabled boolean,
  CONSTRAINT sso_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.users (
  instance_id uuid,
  id uuid NOT NULL,
  aud character varying,
  role character varying,
  email character varying,
  encrypted_password character varying,
  email_confirmed_at timestamp with time zone,
  invited_at timestamp with time zone,
  confirmation_token character varying,
  confirmation_sent_at timestamp with time zone,
  recovery_token character varying,
  recovery_sent_at timestamp with time zone,
  email_change_token_new character varying,
  email_change character varying,
  email_change_sent_at timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  is_super_admin boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  phone text DEFAULT NULL::character varying UNIQUE,
  phone_confirmed_at timestamp with time zone,
  phone_change text DEFAULT ''::character varying,
  phone_change_token character varying DEFAULT ''::character varying,
  phone_change_sent_at timestamp with time zone,
  confirmed_at timestamp with time zone DEFAULT LEAST(email_confirmed_at, phone_confirmed_at),
  email_change_token_current character varying DEFAULT ''::character varying,
  email_change_confirm_status smallint DEFAULT 0 CHECK (email_change_confirm_status >= 0 AND email_change_confirm_status <= 2),
  banned_until timestamp with time zone,
  reauthentication_token character varying DEFAULT ''::character varying,
  reauthentication_sent_at timestamp with time zone,
  is_sso_user boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  is_anonymous boolean NOT NULL DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);