-- ============================================================================
-- CRA OPS database upgrade
-- Target version: 1.1.0
-- ============================================================================
--
-- Purpose:
--   Example minor upgrade showing how to add new schema objects safely.
--
-- Upgrade strategy:
--   - create new objects without breaking existing clients
--   - use IF NOT EXISTS wherever possible
--   - keep the script transactional
--   - separate data migration from schema changes when the change set grows
--
BEGIN;

-- Prevent concurrent upgrade execution within the same database.
SELECT pg_advisory_xact_lock(hashtext('cra_ops_upgrade_1_1_0'));

-- Example: create a lightweight upgrade tracking table if it does not exist.
CREATE TABLE IF NOT EXISTS public.database_release_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version text NOT NULL UNIQUE,
  installed_at timestamptz NOT NULL DEFAULT NOW(),
  notes text
);

-- Example: record the new version.
INSERT INTO public.database_release_log (version, notes)
VALUES ('1.1.0', 'Example minor upgrade that records the installed release')
ON CONFLICT (version) DO UPDATE
SET installed_at = EXCLUDED.installed_at,
    notes = EXCLUDED.notes;

-- Example: keep the application version marker in sync when the settings table exists.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'system_settings'
  ) THEN
    INSERT INTO public.system_settings ("key", "value", updated_at)
    VALUES ('database_version', '1.1.0', NOW())
    ON CONFLICT ("key") DO UPDATE
    SET "value" = EXCLUDED."value",
        updated_at = EXCLUDED.updated_at;
  END IF;
END
$$;

COMMIT;
